name: clima
description: A live weather Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^7.0.2
  http: ^0.13.3
  flutter_spinkit: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/Pacifico-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: assets/SourceSansPro-Regular.ttf
    - family: Newsreader
      fonts:
        - asset: assets/Newsreader_60pt-Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
